.MODEL SMALL
.STACK 100H
.DATA
	MSG1 DB 0DH,0AH,"ENTER THE STRING : ","$"
	MSG2 DB 10,13,"ENTER THE CHARACTER TO FIND : ","$"
	MSG3 DB 10,13,"ENTER THE CHARACTER TO BE REPLACED : ","$"
	NL DB 10,13,"RESULT : ","$"
	STRING DB 20 DUP("$"),"$"		;INPUT STRING.
.CODE
START:
	MOV AX,@DATA
	MOV DS,AX
	
	MOV AH,09H
	LEA DX,MSG1
	INT 21H
	
	MOV AH,0AH
	LEA DX,STRING
	INT 21H
	
	MOV AH,09H
	LEA DX,MSG2
	INT 21H
	
	MOV AH,01H
	INT 21H
	MOV BL,AL ;FIND CHAR.
	
	MOV AH,09H
	LEA DX,MSG3
	INT 21H
	
	MOV AH,01H
	INT 21H
	MOV BH,AL ;REPLACE CHAR.
	
	MOV CL,STRING[01H]
	MOV SI,02H
	
LOOP1: 
	MOV AL,STRING[SI]
	CMP AL,BL	;IF CHAR MATCHES THE FIND. THEN EXE. MOV STATE.
	JNE CLEAR	;ELSE JMP.....
	MOV STRING[SI],BH
		
CLEAR:
	INC SI
	DEC CL
	JNZ LOOP1
	
	LEA DX,NL  
	MOV AH,09H
	INT 21H
	
	LEA DX,STRING[02H] ;O1 IS USED AS USING 0AH,WE GET 1ST 2 BYTES AS NO. OF INPUT CHAR. 
	MOV AH,09H
	INT 21H
	    	
Exit :
    MOV AH,4CH
    INT 21H
END START 